### PR TITLE
ci: migrate to GitHub actions

### PR DESCRIPTION
**Pull request by FrankYang0529**
https://github.com/longhorn/longhorn/issues/8039

### CODE REVIEW

**Comment by innobead** [comment]
@FrankYang0529 have you figured out the necessary credentials with @yangchiu ?

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@yangchiu Please review this as well. Merge this PR after approving it.

**Comment by FrankYang0529** [comment]
> @FrankYang0529 have you figured out the necessary credentials with @yangchiu ?

Yes, already set it. Thank you.

**Review by yangchiu — APPROVED** [review]
LGTM

**Pull request merged**
